name: PR Creation for Main Branch

# Trigger the workflow on pull request creation targeting the main branch
on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify PR creation
        run: |
          echo "A pull request has been created targeting the main branch."
